name = "mopkg"
uuid = "d807b826-8e15-4484-bd8c-e2c336d74c46"
authors = ["justyniaczek"]
version = "0.1.0"

[compat]
julia = "1.4.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
